import { NavGroup } from "../types/navigation";

export const navigation: NavGroup[] = [
    {
        label: "Dashboard",
        icon: "📊",
        items: [{ label: "Overview", path: "/", icon: "🏠" }],
        defaultOpen: true,
    },
    {
        label: "Tenants",
        icon: "🏢",
        items: [
            { label: "Companies", path: "/companies", icon: "🏢" },
        ],
    },
    {
        label: "Infrastructure",
        icon: "🖥️",
        items: [
            { label: "Overview", path: "/infrastructure", icon: "📈" },
            { label: "System", path: "/infrastructure/system", icon: "💻" },
            { label: "Health", path: "/infrastructure/health", icon: "❤️" },
        ],
    },
    {
        label: "Remote Operations",
        icon: "🔗",
        items: [
            { label: "Hosts", path: "/remote/hosts", icon: "🖥️" },
            { label: "Credentials", path: "/remote/credentials", icon: "🔑" },
            { label: "Console", path: "/remote/console", icon: "💻" },
            { label: "Quick Commands", path: "/remote/quick-commands", icon: "⚡" },
            { label: "Execute", path: "/remote/execute", icon: "▶️" },
            { label: "History", path: "/remote/history", icon: "📜" },
            { label: "File Browser", path: "/remote/files", icon: "📂" },
        ],
    },
    {
        label: "Identity",
        icon: "🔐",
        items: [
            { label: "Overview", path: "/identity", icon: "📊" },
            { label: "Active Directory", path: "/identity/active-directory", icon: "🏢" },
            { label: "Microsoft 365", path: "/identity/microsoft-365", icon: "☁️" },
        ],
    },
    {
        label: "Monitoring",
        icon: "📡",
        items: [
            { label: "Overview", path: "/monitoring", icon: "📊" },
            { label: "Hosts", path: "/monitoring/hosts", icon: "🖥️" },
            { label: "Problems", path: "/monitoring/problems", icon: "🚨" },
            { label: "Triggers", path: "/monitoring/triggers", icon: "⚡" },
            { label: "Events", path: "/monitoring/events", icon: "📋" },
            { label: "Host Groups", path: "/monitoring/host-groups", icon: "📁" },
            { label: "Templates", path: "/monitoring/templates", icon: "📐" },
            { label: "Items", path: "/monitoring/items", icon: "📦" },
            { label: "Maps", path: "/monitoring/maps", icon: "🗺️" },
            { label: "Dashboards", path: "/monitoring/dashboards", icon: "📈" },
            { label: "Health", path: "/monitoring/health", icon: "❤️" },
        ],
    },
    {
        label: "Hyper-V",
        icon: "🖥️",
        items: [
            { label: "Overview", path: "/hyperv", icon: "📊" },
            { label: "Virtual Machines", path: "/hyperv/vms", icon: "🖥️" },
            { label: "Networks", path: "/hyperv/networks", icon: "🌐" },
            { label: "Storage", path: "/hyperv/storage", icon: "💾" },
            { label: "Checkpoints", path: "/hyperv/checkpoints", icon: "📸" },
            { label: "Replication", path: "/hyperv/replication", icon: "🔄" },
            { label: "Health", path: "/hyperv/health", icon: "❤️" },
        ],
    },
    {
        label: "Proxmox VE",
        icon: "🐧",
        items: [
            { label: "Overview", path: "/proxmox", icon: "📊" },
            { label: "Health", path: "/proxmox/health", icon: "💓" },
            { label: "Nodes", path: "/proxmox/nodes", icon: "🖧" },
            { label: "Virtual Machines", path: "/proxmox/vms", icon: "🖥️" },
            { label: "Containers", path: "/proxmox/lxc", icon: "📦" },
            { label: "Storage", path: "/proxmox/storage", icon: "💾" },
            { label: "Networks", path: "/proxmox/networks", icon: "🌐" },
            { label: "Snapshots", path: "/proxmox/snapshots", icon: "📸" },
            { label: "Tasks", path: "/proxmox/tasks", icon: "📋" },
        ],
    },
    {
        label: "Veeam Backup",
        icon: "💾",
        items: [
            { label: "Overview", path: "/veeam", icon: "📊" },
            { label: "Health", path: "/veeam/health", icon: "💓" },
            { label: "Jobs", path: "/veeam/jobs", icon: "📋" },
            { label: "Sessions", path: "/veeam/sessions", icon: "📜" },
            { label: "Repositories", path: "/veeam/repositories", icon: "💾" },
            { label: "Servers", path: "/veeam/servers", icon: "🖥️" },
        ],
    },
    {
        label: "AI Operations",
        icon: "🧠",
        items: [
            { label: "Overview", path: "/ai", icon: "📊" },
            { label: "Recommendations", path: "/ai/recommendations", icon: "💡" },
            { label: "Incidents", path: "/ai/incidents", icon: "🚨" },
            { label: "Correlations", path: "/ai/correlations", icon: "🔗" },
            { label: "Health Score", path: "/ai/health", icon: "💓" },
            { label: "History", path: "/ai/history", icon: "📋" },
        ],
    },
    {
        label: "Agents",
        icon: "🤖",
        items: [
            { label: "Overview", path: "/agents", icon: "📊" },
        ],
    },
    {
        label: "Fleet Workspace",
        icon: "🚁",
        items: [
            { label: "Fleet Management", path: "/fleet", icon: "🤖" },
            { label: "Timeline", path: "/fleet/timeline", icon: "📋" },
            { label: "Command Center", path: "/fleet/commands", icon: "⚡" },
            { label: "Health Center", path: "/fleet/health", icon: "❤️" },
            { label: "Plugin Center", path: "/fleet/plugins", icon: "🧩" },
            { label: "Company Workspace", path: "/fleet/companies", icon: "🏢" },
        ],
    },
    {
        label: "Automation",
        icon: "⚙️",
        items: [
            { label: "Overview", path: "/automation", icon: "📊" },
            { label: "Playbooks", path: "/automation/playbooks", icon: "📋" },
            { label: "Executions", path: "/automation/executions", icon: "⚡" },
            { label: "Approvals", path: "/automation/approvals", icon: "✅" },
            { label: "Schedules", path: "/automation/schedules", icon: "⏰" },
            { label: "Triggers", path: "/automation/triggers", icon: "🔔" },
            { label: "Audit Trail", path: "/automation/audit", icon: "📜" },
        ],
    },
    {
        label: "Settings",
        icon: "⚙️",
        items: [
            { label: "General", path: "/settings", icon: "🔧" },
            { label: "Users", path: "/settings/users", icon: "👥" },
            { label: "Integrations", path: "/settings/integrations", icon: "🔌" },
            { label: "Appearance", path: "/settings/appearance", icon: "🎨" },
            { label: "My Dashboard", path: "/settings/dashboard", icon: "📊" },
            { label: "About", path: "/settings/about", icon: "ℹ️" },
        ],
    },
];
