"""add_git_plugin_tables

Revision ID: g1t2r3e4p5o6
Revises: h3y5v6w7x8y9
Create Date: 2026-07-29

Adds Git plugin cache tables: git_repositories, git_branches,
git_commits, git_remotes.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "g1t2r3e4p5o6"
down_revision: Union[str, None] = "h3y5v6w7x8y9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "git_repositories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("integration_profile_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("path", sa.String(length=1000), nullable=False),
        sa.Column("remote_url", sa.String(length=500), nullable=True),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="unknown"),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("path"),
    )
    op.create_index(op.f("ix_git_repositories_id"), "git_repositories", ["id"], unique=False)
    op.create_index(op.f("ix_git_repositories_integration_profile_id"), "git_repositories", ["integration_profile_id"], unique=False)
    op.create_index(op.f("ix_git_repositories_enabled"), "git_repositories", ["enabled"], unique=False)

    op.create_table(
        "git_branches",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("is_remote", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("ahead_of_remote", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("behind_remote", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_commit_id", sa.String(length=100), nullable=True),
        sa.Column("last_commit_message", sa.Text(), nullable=True),
        sa.Column("last_commit_author", sa.String(length=200), nullable=True),
        sa.Column("last_commit_date", sa.String(length=50), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["repo_id"], ["git_repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_git_branches_id"), "git_branches", ["id"], unique=False)
    op.create_index(op.f("ix_git_branches_repo_id"), "git_branches", ["repo_id"], unique=False)
    op.create_index(op.f("ix_git_branches_name"), "git_branches", ["name"], unique=False)

    op.create_table(
        "git_commits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("commit_id", sa.String(length=100), nullable=False),
        sa.Column("short_id", sa.String(length=20), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("author", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("date", sa.String(length=50), nullable=False),
        sa.Column("branch", sa.String(length=200), nullable=True),
        sa.Column("is_merge", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["repo_id"], ["git_repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_git_commits_id"), "git_commits", ["id"], unique=False)
    op.create_index(op.f("ix_git_commits_repo_id"), "git_commits", ["repo_id"], unique=False)
    op.create_index(op.f("ix_git_commits_commit_id"), "git_commits", ["commit_id"], unique=False)
    op.create_index(op.f("ix_git_commits_date"), "git_commits", ["date"], unique=False)

    op.create_table(
        "git_remotes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("repo_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("url", sa.String(length=500), nullable=False),
        sa.Column("push_url", sa.String(length=500), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["repo_id"], ["git_repositories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_git_remotes_id"), "git_remotes", ["id"], unique=False)
    op.create_index(op.f("ix_git_remotes_repo_id"), "git_remotes", ["repo_id"], unique=False)
    op.create_index(op.f("ix_git_remotes_name"), "git_remotes", ["name"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_git_remotes_name"), table_name="git_remotes")
    op.drop_index(op.f("ix_git_remotes_repo_id"), table_name="git_remotes")
    op.drop_index(op.f("ix_git_remotes_id"), table_name="git_remotes")
    op.drop_table("git_remotes")

    op.drop_index(op.f("ix_git_commits_date"), table_name="git_commits")
    op.drop_index(op.f("ix_git_commits_commit_id"), table_name="git_commits")
    op.drop_index(op.f("ix_git_commits_repo_id"), table_name="git_commits")
    op.drop_index(op.f("ix_git_commits_id"), table_name="git_commits")
    op.drop_table("git_commits")

    op.drop_index(op.f("ix_git_branches_name"), table_name="git_branches")
    op.drop_index(op.f("ix_git_branches_repo_id"), table_name="git_branches")
    op.drop_index(op.f("ix_git_branches_id"), table_name="git_branches")
    op.drop_table("git_branches")

    op.drop_index(op.f("ix_git_repositories_enabled"), table_name="git_repositories")
    op.drop_index(op.f("ix_git_repositories_integration_profile_id"), table_name="git_repositories")
    op.drop_index(op.f("ix_git_repositories_id"), table_name="git_repositories")
    op.drop_table("git_repositories")
    # ### end Alembic commands ###
