"""add_hyperv_plugin_tables

Revision ID: h3y5v6w7x8y9
Revises: f4a5b6c7d8e9
Create Date: 2026-07-29

Adds Hyper-V plugin cache tables: hyperv_hosts, hyperv_vms,
hyperv_networks, hyperv_volumes, hyperv_checkpoints.
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "h3y5v6w7x8y9"
down_revision: Union[str, None] = "f4a5b6c7d8e9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "hyperv_hosts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("integration_profile_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("hostname", sa.String(length=500), nullable=False),
        sa.Column("transport", sa.String(length=20), nullable=False, server_default="winrm"),
        sa.Column("port", sa.Integer(), nullable=False, server_default="5985"),
        sa.Column("enabled", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("last_sync_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="unknown"),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("version", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(op.f("ix_hyperv_hosts_id"), "hyperv_hosts", ["id"], unique=False)
    op.create_index(op.f("ix_hyperv_hosts_integration_profile_id"), "hyperv_hosts", ["integration_profile_id"], unique=False)
    op.create_index(op.f("ix_hyperv_hosts_enabled"), "hyperv_hosts", ["enabled"], unique=False)

    op.create_table(
        "hyperv_vms",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("vm_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False, server_default="unknown"),
        sa.Column("cpu_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("memory_assigned_mb", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("memory_startup_mb", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("memory_demand_mb", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("uptime_seconds", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("host_server", sa.String(length=200), nullable=False),
        sa.Column("guest_os", sa.String(length=500), nullable=True),
        sa.Column("creation_time", sa.String(length=50), nullable=True),
        sa.Column("last_checkpoint", sa.String(length=50), nullable=True),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("integration_services_enabled", sa.Boolean(), nullable=False, server_default="false"),
        sa.Column("cpu_usage_percent", sa.Numeric(), nullable=False, server_default="0"),
        sa.Column("disk_read_mbps", sa.Numeric(), nullable=False, server_default="0"),
        sa.Column("disk_write_mbps", sa.Numeric(), nullable=False, server_default="0"),
        sa.Column("network_receive_mbps", sa.Numeric(), nullable=False, server_default="0"),
        sa.Column("network_send_mbps", sa.Numeric(), nullable=False, server_default="0"),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["host_id"], ["hyperv_hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hyperv_vms_id"), "hyperv_vms", ["id"], unique=False)
    op.create_index(op.f("ix_hyperv_vms_host_id"), "hyperv_vms", ["host_id"], unique=False)
    op.create_index(op.f("ix_hyperv_vms_vm_id"), "hyperv_vms", ["vm_id"], unique=False)

    op.create_table(
        "hyperv_networks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("switch_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("switch_type", sa.String(length=20), nullable=False, server_default="external"),
        sa.Column("allow_management_os", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("status", sa.String(length=20), nullable=False, server_default="operational"),
        sa.Column("connected_vms", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("net_adapter", sa.String(length=200), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["host_id"], ["hyperv_hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hyperv_networks_id"), "hyperv_networks", ["id"], unique=False)
    op.create_index(op.f("ix_hyperv_networks_host_id"), "hyperv_networks", ["host_id"], unique=False)
    op.create_index(op.f("ix_hyperv_networks_switch_id"), "hyperv_networks", ["switch_id"], unique=False)

    op.create_table(
        "hyperv_volumes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("disk_id", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=500), nullable=False),
        sa.Column("path", sa.String(length=1000), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("used_bytes", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("type", sa.String(length=20), nullable=False, server_default="vhdx"),
        sa.Column("vm_name", sa.String(length=200), nullable=True),
        sa.Column("attached", sa.Boolean(), nullable=False, server_default="true"),
        sa.Column("format", sa.String(length=20), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["host_id"], ["hyperv_hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hyperv_volumes_id"), "hyperv_volumes", ["id"], unique=False)
    op.create_index(op.f("ix_hyperv_volumes_host_id"), "hyperv_volumes", ["host_id"], unique=False)
    op.create_index(op.f("ix_hyperv_volumes_disk_id"), "hyperv_volumes", ["disk_id"], unique=False)

    op.create_table(
        "hyperv_checkpoints",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("host_id", sa.Integer(), nullable=False),
        sa.Column("checkpoint_id", sa.String(length=100), nullable=False),
        sa.Column("vm_id", sa.String(length=100), nullable=False),
        sa.Column("vm_name", sa.String(length=200), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("checkpoint_type", sa.String(length=20), nullable=False, server_default="standard"),
        sa.Column("creation_time", sa.String(length=50), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("parent_checkpoint_id", sa.String(length=100), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(["host_id"], ["hyperv_hosts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_hyperv_checkpoints_id"), "hyperv_checkpoints", ["id"], unique=False)
    op.create_index(op.f("ix_hyperv_checkpoints_host_id"), "hyperv_checkpoints", ["host_id"], unique=False)
    op.create_index(op.f("ix_hyperv_checkpoints_checkpoint_id"), "hyperv_checkpoints", ["checkpoint_id"], unique=False)
    op.create_index(op.f("ix_hyperv_checkpoints_vm_id"), "hyperv_checkpoints", ["vm_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_hyperv_checkpoints_vm_id"), table_name="hyperv_checkpoints")
    op.drop_index(op.f("ix_hyperv_checkpoints_checkpoint_id"), table_name="hyperv_checkpoints")
    op.drop_index(op.f("ix_hyperv_checkpoints_host_id"), table_name="hyperv_checkpoints")
    op.drop_index(op.f("ix_hyperv_checkpoints_id"), table_name="hyperv_checkpoints")
    op.drop_table("hyperv_checkpoints")

    op.drop_index(op.f("ix_hyperv_volumes_disk_id"), table_name="hyperv_volumes")
    op.drop_index(op.f("ix_hyperv_volumes_host_id"), table_name="hyperv_volumes")
    op.drop_index(op.f("ix_hyperv_volumes_id"), table_name="hyperv_volumes")
    op.drop_table("hyperv_volumes")

    op.drop_index(op.f("ix_hyperv_networks_switch_id"), table_name="hyperv_networks")
    op.drop_index(op.f("ix_hyperv_networks_host_id"), table_name="hyperv_networks")
    op.drop_index(op.f("ix_hyperv_networks_id"), table_name="hyperv_networks")
    op.drop_table("hyperv_networks")

    op.drop_index(op.f("ix_hyperv_vms_vm_id"), table_name="hyperv_vms")
    op.drop_index(op.f("ix_hyperv_vms_host_id"), table_name="hyperv_vms")
    op.drop_index(op.f("ix_hyperv_vms_id"), table_name="hyperv_vms")
    op.drop_table("hyperv_vms")

    op.drop_index(op.f("ix_hyperv_hosts_enabled"), table_name="hyperv_hosts")
    op.drop_index(op.f("ix_hyperv_hosts_integration_profile_id"), table_name="hyperv_hosts")
    op.drop_index(op.f("ix_hyperv_hosts_id"), table_name="hyperv_hosts")
    op.drop_table("hyperv_hosts")
    # ### end Alembic commands ###
